services:
  - type: web
    name: dk-cinema-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn core.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "0"
      - key: DJANGO_ALLOWED_HOSTS
        value: "*"
      - key: CORS_ALLOW_ALL
        value: "1"
      - key: GOOGLE_API_KEY
        sync: false
      - key: DRIVE_ROOT_FOLDER_ID
        sync: false
